<span style="color:blue; font-size:30px;">COSC/MATH 30103 Introduction to Data Science: Numpy Basics</span>

## Numpy Basics

- Numpy is the core library for scientific computing in Python. 
    It provides a high-performance multidimensional array object, and tools for working with these arrays. 

-  Numpy’s main object is the homogeneous multidimensional array.
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. - In NumPy dimensions are called axes. 
- We will talk about how these arrays can be used and their characteristics next.

In [ ]:
# to use numpy, we should first import it
# to import numpy, you can use the following statement
import numpy as np

### Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

The official name of numpy’s array class is __ndarray__. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

__ndarray.ndim__

$\;\;\;\;\;\;$the number of axes (dimensions) of the array.

__ndarray.shape__

$\;\;\;\;\;\;$the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

__ndarray.size__

$\;\;\;\;\;\;$the total number of elements of the array. This is equal to the product of the elements of shape.

__ndarray.dtype__

$\;\;\;\;\;\;$an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

__ndarray.itemsize__

$\;\;\;\;\;\;$the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

__ndarray.data__

$\;\;\;\;\;\;$ the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [ ]:
# We can initialize numpy arrays from nested Python lists, and access elements using square brackets:
a = np.array([1, 2, 3])   # Create a rank 1 array

In [ ]:
a # printing without print statement:only applicable in ipython (interactive-python)

In [ ]:
print(type(a)) # Prints "<class 'numpy.ndarray'>"

In [ ]:
a.shape # "(3,)"

In [ ]:
a.ndim # "1": number of array dimensions

In [ ]:
print(a[0], a[1], a[2])   # Prints "1 2 3"

In [ ]:
a[0] = 5   # Change an element of the array
print(a)   # Prints "[5, 2, 3]"

In [ ]:
# now let's create higher dimensional arrays

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
# Array is 2-dimensional
#                  Dimension-1
#              |----------------|
#              | 1  |  2  |  3  |
#  Dimension-0 |-----------------
#              | 4  |  5  |  6  |

print(b.shape)                     # Prints "(2, 3)"

In [ ]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

In [ ]:
# numpy also provides many functions to create arrays:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

In [ ]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

In [ ]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

In [ ]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

In [ ]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

You can find about other methods of array creation in the documentation form this link: https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation

### Array indexing
Numpy offers several ways to index into arrays.

Slicing is similar to builtin Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
b

In [ ]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"
a

In [ ]:
# You can also mix integer indexing with slice indexing. 
# However, doing so will yield an array of lower rank than the original array.
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]   # return a 1-d (rank 1) view
col_r2 = a[:, 1:2] # return a 2-d (rank2) view but shape is 3 by 1
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

__Integer array indexing:__ When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

a.shape

In [ ]:
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[ [0, 1, 2], 
         [0, 1, 0]
       ]
     )  # Prints "[1 4 5]"
# this will be getting indices [0, 0], [1, 1] and [2, 0] from the array

In [ ]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

In [ ]:
print(a)
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"
# Equivalent to the previous integer array indexing example
# print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix.

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
a
#  [
#    [ 1,  2,  3],
#    [ 4,  5,  6],
#    [ 7,  8,  9],
#    [10, 11, 12]
#  ]


In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

In [ ]:
# Select one element from each row of a using the indices in b
print(a[[0, 1, 2, 3], b])  # Prints "[ 1  6  7 11]" for indices [0,0], [1,2], [2,0], [3,3]

# you can use np.arange(4) instead if [0, 1, 2, 3]

In [ ]:
# You can also mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])
            
print(np.arange(4))

__Boolean array indexing:__ Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

In [ ]:
bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.
            
print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

There are many more neat tricks you can use for indexing numpy arrays. If you want to know more you can read the documentation in this link: https://numpy.org/doc/stable/reference/arrays.indexing.html.

### Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. More on data types can be found in this link: https://numpy.org/doc/stable/reference/arrays.dtypes.html. But for now let's see a brief example:

In [ ]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2.0], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

### Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module.

In [ ]:
# let's create two 2 by 2 float64 arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print('X:\n', x)

print('Y:\n', y)

In [ ]:
# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y) # + is an overloaded operator
print(np.add(x, y)) # you can get the same using np.add

In [ ]:

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))


In [ ]:

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))


In [ ]:

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))


In [ ]:

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

It is important to note that ''*'' is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

Numpy provides many useful functions for performing computations on arrays; one of the most useful is ''sum''.

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by numpy in this link: https://numpy.org/doc/stable/reference/routines.math.html

__Reshaping:__ Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

In [ ]:
# you can get the shape of an array using shape as we discussed
print(a)
np.shape(a)

In [ ]:
print(a.ravel()) # Return a contiguous flattened array.
print(np.ravel(a))

In [ ]:
a = a.reshape((2, 3)) # Gives a new shape to an array without changing its data.
a # 2 by 3 array is transformed to 3 by 2

In [ ]:
a.reshape(1, 6) # return a 1 by 6 (rank 2/2-dimensional) array

In [ ]:
a.reshape(6,) # return a size-6 (1-dimensional) array

### Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print('X:\n', x)
v = np.array([1, 0, 2])
print('v:\n', v)

y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v


print('Add v to each row of X:\n',y)

This works; however when the matrix 'x' is very large, computing an explicit loop in Python could be slow. Adding the vector 'v' to each row of the matrix 'x' is equivalent to forming a matrix 'vv' by stacking multiple copies of 'v' vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 

y = x + vv  # Add x and vv elementwise
print(y)

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
y = x + v  # Add v to each row of x using broadcasting
print(y)

The statement `y = x + v` works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

- If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
- The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
- The arrays can be broadcast together if they are compatible in all dimensions.
- After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
- In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in here: https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs.

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

__Numpy Documentation__: This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the numpy reference (https://numpy.org/doc/stable/user/absolute_beginners.html) to find out much more about numpy.

### Further Clarification on NumPy Broadcasting Rules (with Examples)

Broadcasting works **if and only if** the following conditions hold:

**1) Shapes are compared from the trailing (rightmost) dimension**

Example (valid):
```python
import numpy as np
A = np.ones((3, 4))
B = np.ones((4,))
A + B    # OK
```

Example (invalid):
```python
A = np.ones((3, 4))
B = np.ones((3,))
A + B    #  ValueError
```

Alignment:
(3, 4)
(3,) → (1, 3)

---

**2) If dimensions differ, the smaller shape is left-padded with 1s**

Example:
```python
A = np.ones((5, 4, 3))
B = np.ones((4, 1))
A + B    #OK
```

Implicit alignment:
(5, 4, 3)
(4, 1) → (1, 4, 1)

---

**3) For every aligned dimension: sizes must be equal or one must be 1**

Valid:
```python
A = np.ones((2, 3, 4))
B = np.ones((1, 3, 1))
A + B    # OK
```

Invalid:
```python
A = np.ones((2, 3, 4))
B = np.ones((2, 2, 4))
A + B    # ValueError
```

---

**Compact Rule**

After right-alignment and left-padding with 1s,  
each dimension pair must satisfy:

size_a == size_b  OR  one of them is 1
